apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend
  labels:
    app: portfolio-backend
spec:
  type: ClusterIP
  selector:
    app: portfolio-backend
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
