apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress

spec:
  ingressClassName: nginx

  rules:
    - host: portfolio.local

      http:
        paths:
          - path: /api
            pathType: Prefix

            backend:
              service:
                name: portfolio-backend
                port:
                  number: 3001

          - path: /
            pathType: Prefix

            backend:
              service:
                name: portfolio-frontend
                port:
                  number: 8080
