apiVersion: batch/v1
kind: Job
metadata:
  name: portfolio-migrate
  namespace: javascript
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: a05shwin11/portfolio-backend:v2
          imagePullPolicy: IfNotPresent

          command:
            - node
            - src/db/migrate.js

          envFrom:
            - configMapRef:
                name: portfolio-backend-config

            - secretRef:
                name: portfolio-backend-secret
